### ISSUE TITLE
Households and people at risk of food insecurity

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Covid19#5]
Request for additional tabulations from COVID-19 affected worker ACS data created in issue #1.  

How **many workers** in each of the below jurisdictions* fall into the **lowest three income categories** in your analysis?

- In addition to numbers of workers, how many **people** live in households with workers at risk?
- How many children and seniors are in these households?
- What are the number households with workers at risk by household size (1 person HH, 2 person, etc.)?
- What are the family types of households with workers at risk? 

*Jurisdictions:
- DC
- Montgomery
- Prince George’s
- Fairfax County, Fairfax City, and Falls Church City
- Prince William County, Manassas City, and Manassas Park City
- Arlington County
- Alexandria City

**Comment by rpitingolo** [comment]
@mcohenui thanks for helping out with this task. After you've had a chance to look at the code created from issue #1 please let me know if you want to talk before you get started.

**Comment by mcohenui** [comment]
@ptatian I do have one question here. Do you have a sense for what family type categories they are interested in? single, multi-member, single with children, multi-member with children?

**Comment by ptatian** [comment]
@mcohenui I didn't discuss that specifically with them. The ones you listed seem like a good place to start. But we could also run by them if you think that would be better.

**Comment by mcohenui** [comment]
L:\Libraries\Covid19\Prog\Cvd19_affctd_ind_hh_foodinsecurity.lst
L:\Libraries\Covid19\Prog\Cvd19_affctd_ind_hh_foodinsecurity.log
L:\Libraries\Covid19\Prog\Cvd19_affctd_ind_pop.lst
L:\Libraries\Covid19\Prog\Cvd19_affctd_ind_pop.log
